// Generated by scripts/build-verified-ingested.ts — do not edit by hand.
// Sources: data/musicbrainz/ingested/*.json (api_retrieved, CC0 core metadata).
// These candidates are NOT hand-verified; sample.verified=false.
import type { Candidate } from "./types";

export const VERIFIED_INGESTED: Candidate[] = [
  {
    "id": "mb-ingest-ado-odo",
    "canonical": {
      "artist": "Ado",
      "title": "踊 (Bon-Odo remix)",
      "release": "Ado Nationwide Tour 2023 Mars (live at Nippon Budokan, 2023)",
      "durationSeconds": 203,
      "isrc": "JPPO02602154"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording c66be7df-30e3-4178-8a8d-cbba91593ebb api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: japan)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "japan",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-akmu-how-can-i-love-the-heartbreak-you-re-the-on",
    "canonical": {
      "artist": "Akmu",
      "title": "How can i love the heartbreak, you're the one i love",
      "release": "Akmu Sailing TOUR Live",
      "durationSeconds": 294
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 15a17c40-bc47-41ed-9ade-c23725e0d832 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-balming-tiger-armadillo",
    "canonical": {
      "artist": "Balming TigerOmega SapienByung Un",
      "title": "Armadillo",
      "release": "Armadillo",
      "durationSeconds": 151,
      "isrc": "KRB461900019"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording a72c6fc1-8d6c-4532-a694-547f23d26864 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-black-dresses-creep-u",
    "canonical": {
      "artist": "Black Dresses",
      "title": "creep u",
      "release": "shelter kids will be goth halo",
      "durationSeconds": 104
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 8f5acbdb-0821-4fb9-92e7-f86e0f25c795 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: internet)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "internet",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-blackpink-ddu-du-ddu-du",
    "canonical": {
      "artist": "BLACKPINK",
      "title": "DDU-DU DDU-DU",
      "release": "DDU-DU DDU-DU",
      "durationSeconds": 216
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 7ecfbff0-aabc-48c3-ae1f-a9320fc93a70 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-bts-dynamite",
    "canonical": {
      "artist": "BTS",
      "title": "Dynamite",
      "release": "Proof",
      "durationSeconds": 199,
      "isrc": "USA2P2226583"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 2e3df1b2-7d1e-4300-8bdb-48784a9c40fc api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-burial-archangel",
    "canonical": {
      "artist": "Burial",
      "title": "Archangel",
      "release": "Kode9 at fabric, Mar 15, 2024",
      "durationSeconds": 104,
      "isrc": "US23A9727898"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 1cc9283f-6c07-48ca-a117-51ef8e750e56 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: internet)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "internet",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-dorian-electra-flamboyant",
    "canonical": {
      "artist": "Dorian Electra",
      "title": "Flamboyant",
      "release": "Flamboyant",
      "durationSeconds": 196,
      "isrc": "QM24S1913856"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording bdf5b110-33e6-484d-8781-5399f056e6a1 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: internet)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "internet",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-epik-high-born-hater",
    "canonical": {
      "artist": "Epik High빈지노버벌진트B.IMINOBOBBY",
      "title": "BORN HATER",
      "release": "SHOEBOX",
      "durationSeconds": 237
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording b9d1175c-03e1-4cae-ae5e-ce20856e3852 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-glaive-i-wanna-slam-my-head-against-the-wall",
    "canonical": {
      "artist": "glaive",
      "title": "i wanna slam my head against the wall",
      "release": "i wanna slam my head against the wall",
      "durationSeconds": 117,
      "isrc": "USUG12100804"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 1f3459cb-68f6-4ef0-ab01-d6bc8e66aed2 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: internet)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "internet",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-hannah-diamond-fade-away",
    "canonical": {
      "artist": "Hannah Diamond",
      "title": "Fade Away",
      "release": "Fade Away",
      "durationSeconds": 256,
      "isrc": "UK9951601001"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 0b2ff003-627f-4d8f-90ce-32c54811b961 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: internet)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "internet",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-hikaru-utada-first-love",
    "canonical": {
      "artist": "Hikaru Utada",
      "title": "First Love",
      "release": "HIKARU UTADA SCIENCE FICTION TOUR 2024",
      "durationSeconds": 258,
      "isrc": "JPU902404237"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording ad8c9e90-5340-4301-b275-9b5e5912a6b6 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: japan)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "japan",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-hyukoh-tomboy",
    "canonical": {
      "artist": "HYUKOH",
      "title": "TOMBOY",
      "release": "23",
      "durationSeconds": 242,
      "isrc": "KRC081700004"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 7482dfa6-e65e-4ade-8bf2-157d28e1fd85 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-iu-celebrity",
    "canonical": {
      "artist": "IU",
      "title": "Celebrity",
      "release": "Celebrity",
      "durationSeconds": 195,
      "isrc": "KRA382100464"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 52269c36-7694-4d96-ae3a-1b6ebc7fa945 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-kero-kero-bonito-flamingo",
    "canonical": {
      "artist": "Kero Kero Bonito",
      "title": "Flamingo",
      "release": "Flamingo",
      "durationSeconds": 198,
      "isrc": "GBKPL1522424"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 53cc02a1-2d92-4e57-8a5d-0bee8d5bd43f api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: internet)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "internet",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-miki-matsubara-stay-with-me",
    "canonical": {
      "artist": "CosmicFMMiki Matsubara",
      "title": "Stay With Me",
      "release": "Summer Girls (Deluxe)",
      "durationSeconds": 234
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording c6fc8b0a-6142-43ae-a0f2-ffedee63022c api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: japan)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "japan",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-neon-bunny-seoul",
    "canonical": {
      "artist": "Neon Bunny",
      "title": "Romance In Seoul",
      "release": "Stay Gold",
      "durationSeconds": 231
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 270170e2-7aba-48cf-a73c-af3a0474010c api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-newjeans-attention",
    "canonical": {
      "artist": "NewJeans",
      "title": "Attention",
      "release": "Attention",
      "durationSeconds": 262,
      "isrc": "USA2P2230214"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 554f90c9-c7f3-47be-8712-66243568070c api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-newjeans-hype-boy",
    "canonical": {
      "artist": "NewJeans",
      "title": "Hype boy",
      "release": "New Jeans",
      "durationSeconds": 178,
      "isrc": "USA2P2230222"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 097fffc7-3c8b-4496-ac0b-da999bdaa541 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-oneohtrix-point-never-sticky-drama",
    "canonical": {
      "artist": "Oneohtrix Point Never",
      "title": "Sticky Drama",
      "release": "Bleep: The Top 100 Tracks of 2015",
      "durationSeconds": 258
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording b8071971-88d7-4aba-bf1f-a9c0ff4243d3 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: internet)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "internet",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-radwimps-zenzenzense",
    "canonical": {
      "artist": "RADWIMPS",
      "title": "Zenzenzense (English ver.)",
      "release": "Your Name (Original Motion Picture Soundtrack) (Deluxe Edition)",
      "durationSeconds": 278,
      "isrc": "JPPO01623124"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 4f0a7ae1-0a1d-45f6-98b8-8b7affdd44fd api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: japan)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "japan",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-rina-sawayama-xs",
    "canonical": {
      "artist": "Rina Sawayama",
      "title": "XS",
      "release": "XS",
      "durationSeconds": 201,
      "isrc": "GBK3W1901224"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 5db197d4-c946-4f1e-ba17-bf677bdcafca api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: internet)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "internet",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-silica-gel-desert-eagle",
    "canonical": {
      "artist": "Silica Gel",
      "title": "Desert Eagle",
      "release": "Desert Eagle",
      "durationSeconds": 310,
      "isrc": "KRF252100064"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 1b77302b-2461-4ed8-877d-fe43a44125c2 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-sophie-immaterial",
    "canonical": {
      "artist": "SOPHIE",
      "title": "Immaterial",
      "release": "Treble Fine",
      "durationSeconds": 133
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 05fcac4a-f9d8-4c6f-8c92-815b5ebbbf32 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: internet)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "internet",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-tomoko-aran-midnight-pretenders",
    "canonical": {
      "artist": "Tomoko Aran",
      "title": "Midnight Pretenders",
      "release": "1 Hour of Smooth 70s-80s Japanese Grooves",
      "durationSeconds": 140
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 0af7647d-6e8a-45db-ba87-36809769a6a2 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: japan)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "japan",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-yerin-baek-square",
    "canonical": {
      "artist": "Yerin Baek",
      "title": "Square (2017)",
      "release": "Every letter I sent you",
      "durationSeconds": 261
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording facaa16c-10f1-4287-a977-a6c37bd585e6 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: korea)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "korea",
      "messyCase": false,
      "verified": false
    }
  },
  {
    "id": "mb-ingest-yung-lean-kyoto",
    "canonical": {
      "artist": "Yung Lean",
      "title": "Kyoto",
      "release": "Kyoto",
      "durationSeconds": 270,
      "isrc": "SEY491300022"
    },
    "confidence": 0.85,
    "ambiguity": [],
    "evidence": [
      {
        "field": "artist",
        "score": 1,
        "note": "artist credit from MusicBrainz ws/2"
      },
      {
        "field": "title",
        "score": 1,
        "note": "title from MusicBrainz ws/2 recording lookup"
      },
      {
        "field": "duration",
        "score": 0.9,
        "note": "duration from MusicBrainz recording"
      },
      {
        "field": "musicbrainz",
        "score": 1,
        "note": "recording 60e1da20-def1-4eb5-a3d5-da5b0559fbf5 api_retrieved (not hand-verified)"
      }
    ],
    "availability": {
      "spotify": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "youtube_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "apple_music": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "soundcloud": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "bandcamp": {
        "state": "unknown",
        "note": "platform availability not yet verified"
      },
      "melon": {
        "state": "unknown",
        "note": "regional catalog availability not verified (scene: internet)"
      }
    },
    "sample": {
      "origin": "musicbrainz_ingested",
      "scene": "internet",
      "messyCase": false,
      "verified": false
    }
  }
];
