name: core

on:
  push:
    branches: [main]
    paths:
      - "core/**"
      - ".github/workflows/core.yml"
  pull_request:
    branches: [main]
    paths:
      - "core/**"
      - ".github/workflows/core.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Cargo test
        run: cargo test --workspace
